export const ERROR = {
  USER_NOT_FOUND: "USER_NOT_FOUND",
  LINK_NOT_FOUND: "LINK_NOT_FOUND",
  STYLE_NOT_FOUND: "STYLE_NOT_FOUND",
  GOOGLE_ACOUNT_NOT_VERIFIED: "GOOGLE_ACOUNT_NOT_VERIFIED",
  INTERNAL_SERVER_ERROR: "INTERNAL_SERVER_ERROR",
  DATA_NOT_PROVIDER: "DATA_NOT_PROVIDER",
  INVALID_CREDENTIALS: "INVALID_CREDENTIALS",
  INVALID_LOCAL_PROVIDER: "INVALID_LOCAL_PROVIDER",
  PASSWORD_NOT_FORMAT_VALID: "PASSWORD_NOT_FORMAT_VALID",
  USER_ALREADY_EXIST: "USER_ALREADY_EXIST",
  MISSING_REFRESH_TOKEN: "MISSING_REFRESH_TOKEN",
  MISSING_USER_ID: "MISSING_USER_ID",
  UNAUTHORIZED: "UNAUTHORIZED",
  TOKEN_MISING_OR_INVALID: "TOKEN_MISING_OR_INVALID",
  TOKEN_EXPIRED: "TOKEN_EXPIRED"
};